# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Aracred-actions CI"

on: ["push"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: SourceCred Cache
        uses: actions/cache@v1
        with:
          # cred-action uses *workspace*/sourcecred_data as it's SOURCECRED_DIRECTORY. Only store the cache from that.
          path: sourcecred_data/cache
          key: SC_CACHE-${{ hashFiles('**/project.json') }}-${{ github.run_id }}
          restore-keys: |
            SC_CACHE-${{ hashFiles('**/project.json') }}-
            SC_CACHE-
      - name: Run SourceCred
        uses: vsoch/cred-action@wip-discord-cache
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
        with:
          weights: weights.json
          project: "@AraCred"
          project-file: project.json
          branch-against: master
          automated: "true"
      - uses: "actions/checkout@v2"
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v1"
        with:
          node-version: "${{ matrix.node-version }}"
          GPG_KEY: "${{ secrets.GPG_KEY }}"
      - name: Decrypt secret keys
        run: ./decrypt_secret.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Install Aracred
        run: npm ci
      - name: Install Aragon
        run: npm install -g @aragon/cli
      - name: Decrypt keys
        run: ./decrypt_secret.sh
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Creating web3 provider config
        run: npm run secrets
      - name: Prepare transaction
        run: npm run prepTX
      - name: SourceCred Grain
        run: cat transactionSettings.json
      - name: Sending Transaction
        run: node ./src/mint.js | sh
