name: "Run aragonCLI"

on:
  # Trigger on merging to master.
  push:
    branches:
      - transfer
  # Runs the CLI At 00:00 on Sunday.
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: "actions/checkout@v2"
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v1"
        with:
          node-version: "${{ matrix.node-version }}"
          INFURA_KEY: "${{ secrets.INFURA_KEY }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
      - name: Setup aragonCLI signer
        run: node ./src/setupAragon.js
        env:
          INFURA_KEY: "${{ secrets.INFURA_KEY }}"
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
      - name: Install Aracred
        run: npm ci
      - name: Install Aragon
        run: npm install -g @aragon/cli
      - name: Prepare transaction
        run: node ./src/processGrain.js
      - name: Sending Transaction
        run: node ./src/runAction.js | sh
